### ISSUE TITLE
Is the project terminated?

### ISSUE THREAD

**Issue by Kavey** [plsfixrito/BattleRight#1]
Hello, I have no clue where to contact you so I am trying there:

recently the website went down, as well as the auth server a bit later, are you giving up on the project? :(

**Comment by plsfixrito** [comment]
We're on the process of transferring the domain into a new host.
There are delays and some issues we're working on resolving them.
Both Auth and website will be up as soon as possible.

**Comment by Kavey** [comment]
Thanks you for that very fast response, have a great evening :)

**Comment by plsfixrito** [comment]
Hello,
The platform is still alive, we're facing some issues on the website end.
You can still login and use the tool if you remember your old Auth key !
